In [1]:
import numpy as np

Bài 1

In [3]:
arr = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
print(arr.shape)
print(matrix.shape)

(3,)
(2, 3)


In [6]:
print(arr.dtype)
float_arr = np.array([1.0, 7.0], dtype=np.float32)
print(float_arr.dtype)

int64
float32


In [8]:
zeros = np.zeros((2, 3))
one = np.ones((3, ))
range_arr = np.arange(0, 10, 2)
lin_arr = np.linspace(0, 1, 5)

In [10]:
print(zeros)
print(one) 
print(range_arr)
print(lin_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [11]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr[1:4])

arr[2]= 10

matrix = np.array([[1, 2], [3, 4]])

print(matrix[0, 1])

[1 2 3 4 5]
[2 3 4]
2


In [13]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

print(a + b)
print(a - b)
print(a @ b)

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

print(np.dot(mat1, mat2))

[4 6 8]
[-2 -2 -2]
26
[[19 22]
 [43 50]]


In [14]:
data = np.array([1, 2, 3, 4, 5])
print(np.mean(data))
print(np.sum(data))
print(np.max(data))
print(np.std(data))

3.0
15
5
1.4142135623730951


In [15]:
arr = np.arange(6)
print(arr)

matrix = arr.reshape(2, 3)
print(matrix)

flat = matrix.flatten()
print(flat)

tranposed = matrix.T
print(tranposed)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]


Bài 2:

In [17]:
arr = np.array([1, -2, 3, -4, 5, -6])

result1 = np.where(arr < 0, 0, arr)
print(result1)

result2 = np.where(arr%2==0, "even", "odd")
print(result2)

result3 = np.where(arr>2)
print(result3)

[1 0 3 0 5 0]
['odd' 'even' 'odd' 'even' 'odd' 'even']
(array([2, 4]),)


Bài 3:

In [22]:
temps = np.array([25, 28, 30, 22, 35, 18, 20])

conditions = [temps < 20, (temps >= 20) & (temps < 30), temps >= 30]
choices = ["Cold", "Mild", "Hot"]

result = np.select(conditions, choices, default="None")

print(result)

['Mild' 'Mild' 'Hot' 'Mild' 'Hot' 'Cold' 'Mild']


Bài 4:

In [24]:
mat = np.random.randint(1, 100, (5, 5))

def caculate_row(row):
    return (row - np.min(row)) / (np.max(row) - np.min(row))

mat_2 = np.apply_along_axis(caculate_row, axis=1, arr=mat)

def softmax(col):
    exp_col = np.exp(col)
    return exp_col / np.sum(col)

softmax_mat = np.apply_along_axis(softmax, axis=0, arr=mat)

print(mat)
print(mat_2)
print(softmax_mat)

[[73 87 23 49 99]
 [60 77 47 94 65]
 [15 46 16 57  8]
 [48 62 90 48 85]
 [79 46 31 22 23]]
[[0.65789474 0.84210526 0.         0.34210526 1.        ]
 [0.27659574 0.63829787 0.         1.         0.38297872]
 [0.14285714 0.7755102  0.16326531 1.         0.        ]
 [0.         0.33333333 1.         0.         0.88095238]
 [1.         0.42105263 0.15789474 0.         0.01754386]]
[[1.83723405e+29 1.91070133e+35 4.70763452e+07 7.06424656e+18
  3.53179654e+40]
 [4.15275414e+23 8.67457061e+30 1.24701106e+18 2.46784304e+38
  6.05317587e+25]
 [1.18873359e+04 2.98620108e+17 4.29280701e+04 2.10582222e+22
  1.06462785e+01]
 [2.55154033e+18 2.65357128e+24 5.89566809e+36 2.59879108e+18
  2.93679026e+34]
 [7.41193115e+31 2.98620108e+17 1.40332607e+11 1.32774550e+07
  3.48028695e+07]]


Bài 5:

In [34]:
data = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])

data_filled = data.copy()
for col in range(data.shape[1]):
    col_mean = np.nanmean(data[:, col])  
    data_filled[:, col] = np.where(np.isnan(data[:, col]), col_mean, data[:, col])

print(data_filled)

col_means_filled = np.mean(data_filled, axis=0)
col_stds = np.std(data_filled, axis=0)
z_score = (data_filled - col_means_filled) / col_stds

col_mins = np.min(data_filled, axis=0)
col_maxs = np.max(data_filled, axis=0)
min_max_scaled = (data_filled - col_mins) / (col_maxs - col_mins)

print(z_score)
print(min_max_scaled)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]
[[-1.22474487 -1.22474487  0.        ]
 [ 0.          0.         -1.22474487]
 [ 1.22474487  1.22474487  1.22474487]]
[[0.  0.  0.5]
 [0.5 0.5 0. ]
 [1.  1.  1. ]]
